[tool.poetry]
name = "test-task"
version = "0.1.0"
description = ""
authors = ["AlexanderLevkin <levkin.a@promail366.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
